app = "your-app-name"  # Replace this with your Fly.io app name

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "python:3.10-slim"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
